### ISSUE TITLE
Handle node death

### ISSUE THREAD

**Issue by cbrxyz** [uf-mil/axros#16]
When a node attempts to grab a topic, but the node publishing to that topic has died, an error like this is shown:
```py
Traceback (most recent call last):
  File "/home/parallels/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "uvloop/loop.pyx", line 2024, in create_connection
  File "uvloop/loop.pyx", line 2001, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/parallels/catkin_ws/src/mil/mil_common/axros/axros/src/axros/rosxmlrpc.py", line 60, in request
    response = await self.session.post(
  File "/home/parallels/.local/lib/python3.8/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/home/parallels/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/parallels/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/parallels/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/home/parallels/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/parallels/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host ubuntu-linux-20-04-desktop:34637 ssl:default [Connection refused]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/parallels/catkin_ws/src/mil/mil_common/axros/axros/src/axros/subscriber.py", line 272, in _publisher_thread
    value = await proxy.request_topic(self._name, [["TCPROS"]])
  File "/home/parallels/catkin_ws/src/mil/mil_common/axros/axros/src/axros/rosxmlrpc.py", line 311, in remote_caller
    status_code, status_message, value = await getattr(
  File "/home/parallels/catkin_ws/src/mil/mil_common/axros/axros/src/axros/rosxmlrpc.py", line 42, in __call__
    ret = await self.send(self.name, args)
  File "/home/parallels/catkin_ws/src/mil/mil_common/axros/axros/src/axros/rosxmlrpc.py", line 148, in __request
    response = await self.transport.request(self.uri, request)
  File "/home/parallels/catkin_ws/src/mil/mil_common/axros/axros/src/axros/rosxmlrpc.py", line 75, in request
    raise XMLRPCException(e, request_body, self.node_handle) from e
axros.rosxmlrpc.XMLRPCException: Exception in axros related to /mission_runner: An error occurred in the XMLRPC communication. The '/mission_runner' node attempted to call 'requestTopic' resulting in an error. For help resolving this exception, please see the axros documentation.

It appears the node may not be able to find a node publishing the topic it is attempting to listen to. This likely means that the node publishing to the topic has died. Please check the publisher to the topic for issues and restart ROS.

Request body: b"<?xml version='1.0'?>\n<methodCall>\n<methodName>requestTopic</methodName>\n<params>\n<param>\n<value><string>/mission_runner</string></value>\n</param>\n<param>\n<value><string>/dvl/range</string></value>\n</param>\n<param>\n<value><array><data>\n<value><array><data>\n<value><string>TCPROS</string></value>\n</data></array></value>\n</data></array></value>\n</param>\n</params>\n</methodCall>\n"
```

It's a lot, and isn't super focused/helpful. It would be great if the error text at the bottom could be more direct in insisting that the `X` node publishing to topic `Y` has died. Also, it might be nice to not print the request body, as it's very hard to read and often contains information that could be better formatted into a human-readable string.

**Comment by cbrxyz** [comment]
Closed in 55395aa
